apiVersion: apps/v1
kind: Deployment 
metadata: #Dictionary
  name: maharshi-deployment
spec: # Dictionary
  replicas: 3
  selector:
    matchLabels:
      app: myapp3
  template:  
    metadata: # Dictionary
      name: maharshi-pod
      labels: # Dictionary
        app: myapp3  # Key value paids
    spec:
      containers: # List
        - name: maharshi-container
          image: sepaks.azurecr.io/maharshiapp:1.0.0
          ports: 
            - containerPort: 80
      imagePullSecrets:
        - name: acr-secret
